### PR TITLE
Feature/editor context menu

### PR DESCRIPTION
**Pull request by goldsborough**
Refactors the Editor and gives it a context menu

### CODE REVIEW

**Review by andizimmerer — COMMENTED** [review]
the text in the first line of the editor is not visible. there is something that overlays this line (and only the first line).

line_overlay

both lines contain `gagagag` (the lower part of the `g` is still visible in the first line.

--edit---
Everything works fine after updating to the latest theme.

**Comment by Jibbow** [comment]
both lines contain `gagagaga` (the lower part of the `g` is visible.

**Comment by FelixOpolka** [comment]
Binary formatting in registers is broken. It works on master, though.

**Review by FelixOpolka — APPROVED** [review]
When pressing "Copy All", the cursor is moved to end of file. Maybe you can restore its previous position after copying. Otherwise everything looks good!

**Pull request merged**
