### PR TITLE
symbol for write protected memory cells

### PR DESCRIPTION
**Pull request by andizimmerer**

### CODE REVIEW

**Review by k-lukas — APPROVED** [review]

**Comment by ErikP0** [comment]
Uknown Characters This happens on Windows with Qt 5.8 and on my Ubuntu VM with (broken) Qt 5.6.2.
Can you reproduce this, or am I missing a font?

**Comment by janschopohl** [comment]
In the default theme, for me it looks like this:
grafik

However, there is a different symbol for the presentation theme. Is this on purpose?
grafik

The alignement is also not quite perfect :wink:

**Comment by andizimmerer** [comment]
@ErikP0 good point! Is fixed now.
@janschopohl yes, was intended, but now I changed both to the same symbol (and I've changed the alignment a little) ;)

**Review by ErikP0 — APPROVED** [review]
Ok after manually updating the them, it works!

**Pull request merged**
